#===============================================================================
# MixNSSolver -- top-level Makefile
#
# Targets:
#   make / make all         serial mixed solver            -> bin/mixsolver
#   make mpi                MPI    mixed solver            -> bin/mixsolver_mpi
#   make structured         serial structured-only solver  -> bin/struct_solver
#   make structured_mpi     MPI    structured-only solver  -> bin/struct_solver_mpi
#   make unstructured       serial unstructured-only       -> bin/uns_solver
#   make unstructured_mpi   MPI    unstructured-only       -> bin/uns_solver_mpi
#   make common             compile common modules only (serial sanity check)
#   make common_mpi         same, MPI toolchain
#   make clean              remove build/ and bin/
#   make help
#
# Options:
#   DEBUG=1   use -O0 -g -fcheck=all -fbacktrace instead of -O2
#
# Build layout:
#   build/ser/{common,structured,unstructured,coupling}/*.o and *.d
#   build/ser/mod/*.mod
#   build/mpi/...            (same layout; mpif90, -DHAVE_MPI)
# Separate serial/MPI trees mean switching between them needs NO 'make clean'.
#
# Porting conventions (important for phases 2 and 3):
#   1. Fortran module names must be GLOBALLY UNIQUE: every module lives in one
#      shared -J directory, so use the mod_struct_* / mod_uns_* prefixes and
#      drop each source solver's private mod_precision (use common/).
#   2. Files compiled ONLY in the MPI build must end in '_mpi.f90'; they are
#      automatically filtered out of serial builds.
#   3. Files shared by both builds may guard MPI code with '#ifdef HAVE_MPI'
#      (preprocessing is enabled in both trees; MPI builds define HAVE_MPI).
#   4. Module dependencies are auto-generated by gfortran (-MMD -MP); no
#      hand-maintained object ordering is required for incremental builds.
#   5. Parallel builds: on a PRISTINE tree (no .d files yet) a plain 'make -j'
#      cannot know inter-module order. Foundational modules in BOOTSTRAP_ORDER
#      get explicit edges below; if a later phase adds many interdependent
#      modules at once, either run the first build with 'make -j1' (after that
#      .d files make -j safe), or add explicit edges in the section marked
#      "PRISTINE-BUILD EDGES".
#===============================================================================

FC      := gfortran
MPIFC   := mpif90

# -----------------------------------------------------------------------------
# External libraries
# -----------------------------------------------------------------------------
LIBDIR     := lib
METIS_LIB  := $(LIBDIR)/metis/libmetis.a
TECIO_LIB  := $(LIBDIR)/tecplot/libtecio.a
PARMETIS_LIB := $(LIBDIR)/parmetis/libparmetis_gnu_mpi.a

# NOTE on ParMETIS: the prebuilt archive in lib/parmetis targets the MPICH ABI
# (MPI_Comm = int), while this system uses OpenMPI 4.1.6 (MPI_Comm = void*);
# linking it crashes inside MPI_Comm_rank.  Consistent with UNSSolverProj,
# partitioning uses SERIAL METIS on rank 0.  $(PARMETIS_LIB) is therefore not
# linked by default; re-enable here only after rebuilding ParMETIS against
# the local OpenMPI.

# -----------------------------------------------------------------------------
# Flags
# -----------------------------------------------------------------------------
DEBUG ?= 0
ifeq ($(DEBUG),1)
  OPT := -O0 -g -fcheck=all -fbacktrace
else
  OPT := -O2
endif

# -cpp is required both for -MMD dependency generation and '#ifdef HAVE_MPI'.
# -ffree-line-length-none: the ported OpenCFD-EC sources contain a few long
# source lines (>132 cols); harmless for newly written f2008 code.
FFLAGS     := -cpp -std=f2008 -Wall -ffree-line-length-none $(OPT)

S := build/ser
M := build/mpi

FFLAGS_S   := $(FFLAGS) -J$(S)/mod
FFLAGS_M   := $(FFLAGS) -DHAVE_MPI -J$(M)/mod

# Archives are pulled in by the linker only when symbols are referenced,
# so listing conditionally-existing ones unconditionally is harmless.
LDLIBS_S   := $(wildcard $(TECIO_LIB)) -lstdc++ -lm
LDLIBS_M   := $(wildcard $(METIS_LIB)) $(wildcard $(TECIO_LIB)) -lstdc++ -lm

# -----------------------------------------------------------------------------
# Source discovery
# -----------------------------------------------------------------------------
COMMON_F := $(wildcard src/common/*.f90)
STRUCT_F := $(wildcard src/structured/*.f90)
UNS_F    := $(wildcard src/unstructured/*.f90)
COUPL_F  := $(wildcard src/coupling/*.f90)

# Standalone driver programs (appear in later phases).
MAIN_MIX_F    := $(wildcard src/main.f90)
MAIN_STRUCT_F := $(wildcard src/structured/main.f90)
MAIN_UNS_F    := $(wildcard src/unstructured/main_uns.f90)
MAIN_UNS_MPI_F:= $(wildcard src/unstructured/main_uns_mpi.f90)
# phase-4 coupling geometry test driver (links structured + unstructured + coupling)
MAIN_MATCH_F  := $(wildcard src/coupling/test_match.f90)
# phase-5 units + exchange unit test (links common + coupling only, serial)
MAIN_UNITS_TEST_F := $(wildcard src/coupling/test_units_exchange.f90)
# phase-6 MPI coupling-protocol test (links common + coupling only, MPI tree)
MAIN_COUPL_TEST_F := $(wildcard src/coupling/test_coupling_exchange.f90)
# phase-14 interface-closure unit test (common only: mod_iface_law is pure)
MAIN_IFLAW_TEST_F := $(wildcard src/coupling/test_iface_law.f90)
# self-dispatching zero-argument executable (bin/mixnsolver[_mpi])
MAIN_DISPATCH_F := $(wildcard src/main_dispatch.f90)

# Library sources = every module file except standalone mains.
# MPI-only files ('*_mpi.f90') are excluded from the serial tree ONLY for the
# unstructured solver: the structured solver lifted from OpenCFD-EC is
# intrinsically MPI (12 files call MPI_* directly, including the 3 *_mpi.f90
# communication/partition files), so its full source set is built with mpif90
# in BOTH trees -- 'make structured' is simply the single-process-capable MPI
# build (run with mpirun -np 1).  The HAVE_MPI macro distinguishes the trees.
#
# BOOTSTRAP_ORDER: on a pristine tree no .d files exist yet, so make compiles
# in list order. Foundational common modules are listed here; the structured
# solver's internal module ordering has explicit edges in the
# "PRISTINE-BUILD EDGES" section below.  From the second build on the
# auto-generated .d files take over.
BOOTSTRAP_ORDER := $(wildcard src/common/mod_precision.f90) \
                   $(wildcard src/common/mod_constants.f90) \
                   $(wildcard src/common/mod_reference_state.f90) \
                   $(wildcard src/common/mod_interface.f90)
sort_boot = $(BOOTSTRAP_ORDER) $(filter-out $(BOOTSTRAP_ORDER),$1)

# Unstructured serial sources drop *_mpi.f90 and MPI-dependent modules.
UNS_LIB_S := $(filter-out %_mpi.f90,$(UNS_F))
UNS_LIB_S := $(filter-out \
  src/unstructured/mod_uns_gather.f90 \
  src/unstructured/mod_uns_halo.f90 \
  src/unstructured/mod_uns_restart.f90 \
  src/unstructured/mod_uns_local_mesh.f90 \
  src/unstructured/mod_uns_partition.f90 \
  src/unstructured/mod_uns_mpi_core.f90,$(UNS_LIB_S))

LIB_SRCS_S := $(call sort_boot,$(filter-out $(MAIN_STRUCT_F) $(MAIN_UNS_F) $(MAIN_UNS_MPI_F) $(MAIN_MATCH_F) $(MAIN_UNITS_TEST_F) $(MAIN_COUPL_TEST_F) $(MAIN_IFLAW_TEST_F) $(MAIN_DISPATCH_F), \
                         $(COMMON_F) $(STRUCT_F) $(UNS_LIB_S) $(COUPL_F)))
LIB_SRCS_M := $(call sort_boot,$(filter-out $(MAIN_STRUCT_F) $(MAIN_UNS_F) $(MAIN_UNS_MPI_F) $(MAIN_MATCH_F) $(MAIN_UNITS_TEST_F) $(MAIN_COUPL_TEST_F) $(MAIN_IFLAW_TEST_F) $(MAIN_DISPATCH_F), \
                          $(COMMON_F) $(STRUCT_F) $(UNS_F) $(COUPL_F)))

LIB_OBJ_S := $(patsubst src/%.f90,$(S)/%.o,$(LIB_SRCS_S))
LIB_OBJ_M := $(patsubst src/%.f90,$(M)/%.o,$(LIB_SRCS_M))

MIX_OBJ_S  := $(LIB_OBJ_S) $(patsubst src/%.f90,$(S)/%.o,$(MAIN_MIX_F))
MIX_OBJ_M  := $(LIB_OBJ_M) $(patsubst src/%.f90,$(M)/%.o,$(MAIN_MIX_F))

DISPATCH_OBJ_S := $(LIB_OBJ_S) $(patsubst src/%.f90,$(S)/%.o,$(MAIN_DISPATCH_F))
DISPATCH_OBJ_M := $(LIB_OBJ_M) $(patsubst src/%.f90,$(M)/%.o,$(MAIN_DISPATCH_F))

STRUCT_OBJ_S := $(filter $(S)/common/%.o $(S)/structured/%.o,$(LIB_OBJ_S)) \
                $(patsubst src/%.f90,$(S)/%.o,$(MAIN_STRUCT_F))
STRUCT_OBJ_M := $(filter $(M)/common/%.o $(M)/structured/%.o,$(LIB_OBJ_M)) \
                $(patsubst src/%.f90,$(M)/%.o,$(MAIN_STRUCT_F))

UNS_OBJ_S := $(filter $(S)/common/%.o $(S)/unstructured/%.o,$(LIB_OBJ_S)) \
             $(patsubst src/%.f90,$(S)/%.o,$(MAIN_UNS_F))
UNS_OBJ_M := $(filter $(M)/common/%.o $(M)/unstructured/%.o,$(LIB_OBJ_M)) \
             $(patsubst src/%.f90,$(M)/%.o,$(MAIN_UNS_MPI_F))

# phase-4 coupling geometry test: structured (MPI) + unstructured (MPI) + coupling
MATCH_OBJ_M := $(filter $(M)/common/%.o $(M)/structured/%.o $(M)/unstructured/%.o $(M)/coupling/%.o,$(LIB_OBJ_M)) \
               $(patsubst src/%.f90,$(M)/%.o,$(MAIN_MATCH_F))

# phase-5 units/exchange test: common + coupling.  The coupling objects are
# MPI-intrinsic (mod_coupling_exchange), so this test is LINKED with $(MPIFC)
# even though it is a standalone serial test -- exactly like bin/mixsolver, the
# ser tree is the 'single-process-capable MPI build' (run with -np 1).
UNITS_TEST_OBJ_S := $(filter-out $(S)/coupling/mod_mix_driver.o,$(filter $(S)/common/%.o $(S)/coupling/%.o,$(LIB_OBJ_S))) \
                    $(patsubst src/%.f90,$(S)/%.o,$(MAIN_UNITS_TEST_F))

# phase-6 MPI coupling-protocol test: common + coupling (MPI tree)
COUPL_TEST_OBJ_M := $(filter-out $(M)/coupling/mod_mix_driver.o,$(filter $(M)/common/%.o $(M)/coupling/%.o,$(LIB_OBJ_M))) \
                    $(patsubst src/%.f90,$(M)/%.o,$(MAIN_COUPL_TEST_F))

# phase-14 interface-closure unit test: common only (the closures are pure)
IFLAW_TEST_OBJ_S := $(filter $(S)/common/%.o,$(LIB_OBJ_S)) \
                    $(patsubst src/%.f90,$(S)/%.o,$(MAIN_IFLAW_TEST_F))

# -----------------------------------------------------------------------------
# Build directories
# -----------------------------------------------------------------------------
OBJDIRS_S := $(S)/mod $(S)/common $(S)/structured $(S)/unstructured $(S)/coupling
OBJDIRS_M := $(M)/mod $(M)/common $(M)/structured $(M)/unstructured $(M)/coupling
ALLDIRS   := $(OBJDIRS_S) $(OBJDIRS_M) bin

$(ALLDIRS):
	mkdir -p $@

# -----------------------------------------------------------------------------
# Compilation rules (auto-generated .d files carry module dependencies)
# -----------------------------------------------------------------------------
$(S)/%.o: src/%.f90 | $(ALLDIRS)
	$(FC) $(FFLAGS_S) -MMD -MP -c $< -o $@

$(M)/%.o: src/%.f90 | $(ALLDIRS)
	$(MPIFC) $(FFLAGS_M) -MMD -MP -c $< -o $@

# Structured solver is MPI-intrinsic: build it with mpif90 even in the "ser"
# tree (no HAVE_MPI there, but MPI_Init is always called; run with -np 1).
# The lifted OpenCFD-EC sources were modernised in phase 2b (explicit-shape
# dummies receive whole arrays, mixed-kind literals suffixed with _PRE_EC,
# isnan -> ieee_is_nan, OPEN access=append -> position=append, missing FORMAT
# commas added), so they now compile under the project-wide -std=f2008 and the
# per-tree -std=legacy override is removed.
$(S)/structured/%.o: src/structured/%.f90 | $(ALLDIRS)
	$(MPIFC) $(FFLAGS_S) -MMD -MP -c $< -o $@

$(M)/structured/%.o: src/structured/%.f90 | $(ALLDIRS)
	$(MPIFC) $(FFLAGS_M) -MMD -MP -c $< -o $@

# The coupling layer (mod_coupling_exchange) and the mixed driver (main.f90)
# call MPI_* unconditionally -- the cross-group exchange is inherently
# multi-rank -- so, exactly like src/structured above, build them with mpif90 in
# BOTH trees; 'make all' is the single-process-capable MPI build (bin/mixsolver
# is already LINKED with $(MPIFC) below).  main.f90's restart-save path is the
# only reference to the MPI-only uns restart stack (mod_uns_restart ->
# mod_uns_mpi_core/partition/local_mesh); it is guarded by '#ifdef HAVE_MPI' so
# the serial tree need not link those modules.
$(S)/coupling/%.o: src/coupling/%.f90 | $(ALLDIRS)
	$(MPIFC) $(FFLAGS_S) -MMD -MP -c $< -o $@

$(S)/main.o: src/main.f90 | $(ALLDIRS)
	$(MPIFC) $(FFLAGS_S) -MMD -MP -c $< -o $@

# The self-dispatching executable calls MPI_* unconditionally and links the
# full common+structured+unstructured+coupling stack; build it with mpif90 in
# both trees exactly like main.o, 'make all' is the single-process build.
$(S)/main_dispatch.o: src/main_dispatch.f90 | $(ALLDIRS)
	$(MPIFC) $(FFLAGS_S) -MMD -MP -c $< -o $@

# -----------------------------------------------------------------------------
# Executables
# -----------------------------------------------------------------------------
bin/mixsolver: $(MIX_OBJ_S) | bin
	@test -f src/main.f90 || { \
	  echo "ERROR: src/main.f90 does not exist yet (scheduled for phase 6)."; \
	  echo "       Use 'make common' to build the modules currently present."; \
	  exit 1; }
	$(MPIFC) $(FFLAGS_S) -o $@ $(MIX_OBJ_S) $(LDLIBS_S)

bin/mixsolver_mpi: $(MIX_OBJ_M) | bin
	@test -f src/main.f90 || { \
	  echo "ERROR: src/main.f90 does not exist yet (scheduled for phase 6)."; \
	  echo "       Use 'make common_mpi' to build the modules currently present."; \
	  exit 1; }
	$(MPIFC) $(FFLAGS_M) -o $@ $(MIX_OBJ_M) $(LDLIBS_M)

bin/mixnsolver: $(DISPATCH_OBJ_S) | bin
	@test -f src/main_dispatch.f90 || { \
	  echo "ERROR: src/main_dispatch.f90 does not exist yet."; \
	  exit 1; }
	$(MPIFC) $(FFLAGS_S) -o $@ $(DISPATCH_OBJ_S) $(LDLIBS_S)

bin/mixnsolver_mpi: $(DISPATCH_OBJ_M) | bin
	@test -f src/main_dispatch.f90 || { \
	  echo "ERROR: src/main_dispatch.f90 does not exist yet."; \
	  exit 1; }
	$(MPIFC) $(FFLAGS_M) -o $@ $(DISPATCH_OBJ_M) $(LDLIBS_M)

bin/struct_solver: $(STRUCT_OBJ_S) | bin
	@test -f src/structured/main.f90 || { \
	  echo "ERROR: src/structured/main.f90 does not exist yet (scheduled for phase 2)."; \
	  exit 1; }
	$(MPIFC) $(FFLAGS_S) -o $@ $(STRUCT_OBJ_S) $(LDLIBS_S)

bin/struct_solver_mpi: $(STRUCT_OBJ_M) | bin
	@test -f src/structured/main.f90 || { \
	  echo "ERROR: src/structured/main.f90 does not exist yet (scheduled for phase 2)."; \
	  exit 1; }
	$(MPIFC) $(FFLAGS_M) -o $@ $(STRUCT_OBJ_M) $(LDLIBS_M)

bin/uns_solver: $(UNS_OBJ_S) | bin
	@test -f src/unstructured/main_uns.f90 || { \
	  echo "ERROR: src/unstructured/main_uns.f90 does not exist yet (scheduled for phase 3)."; \
	  exit 1; }
	$(FC) $(FFLAGS_S) -o $@ $(UNS_OBJ_S) $(LDLIBS_S)

bin/uns_solver_mpi: $(UNS_OBJ_M) | bin
	@test -f src/unstructured/main_uns_mpi.f90 || { \
	  echo "ERROR: src/unstructured/main_uns_mpi.f90 does not exist yet (scheduled for phase 3)."; \
	  exit 1; }
	$(MPIFC) $(FFLAGS_M) -o $@ $(UNS_OBJ_M) $(LDLIBS_M)

bin/match_test: $(MATCH_OBJ_M) | bin
	@test -f src/coupling/test_match.f90 || { \
	  echo "ERROR: src/coupling/test_match.f90 does not exist yet (phase 4)."; \
	  exit 1; }
	$(MPIFC) $(FFLAGS_M) -o $@ $(MATCH_OBJ_M) $(LDLIBS_M)

bin/units_test: $(UNITS_TEST_OBJ_S) | bin
	@test -f src/coupling/test_units_exchange.f90 || { \
	  echo "ERROR: src/coupling/test_units_exchange.f90 does not exist yet (phase 5)."; \
	  exit 1; }
	$(MPIFC) $(FFLAGS_S) -o $@ $(UNITS_TEST_OBJ_S) $(LDLIBS_S)

bin/coupling_test: $(COUPL_TEST_OBJ_M) | bin
	@test -f src/coupling/test_coupling_exchange.f90 || { \
	  echo "ERROR: src/coupling/test_coupling_exchange.f90 does not exist yet (phase 6)."; \
	  exit 1; }
	$(MPIFC) $(FFLAGS_M) -o $@ $(COUPL_TEST_OBJ_M) $(LDLIBS_M)

bin/iface_law_test: $(IFLAW_TEST_OBJ_S) | bin
	@test -f src/coupling/test_iface_law.f90 || { \
	  echo "ERROR: src/coupling/test_iface_law.f90 does not exist yet (phase 14)."; \
	  exit 1; }
	$(MPIFC) $(FFLAGS_S) -o $@ $(IFLAW_TEST_OBJ_S) $(LDLIBS_S)

# -----------------------------------------------------------------------------
# Phony targets
# -----------------------------------------------------------------------------
.PHONY: all mpi structured structured_mpi unstructured unstructured_mpi \
        common common_mpi clean help match_test units_test coupling_test \
        iface_law_test mixnsolver mixnsolver_mpi

all:        bin/mixsolver
mpi:        bin/mixsolver_mpi
mixnsolver: bin/mixnsolver
mixnsolver_mpi: bin/mixnsolver_mpi
structured: bin/struct_solver
structured_mpi: bin/struct_solver_mpi
unstructured:   bin/uns_solver
unstructured_mpi: bin/uns_solver_mpi

common: $(filter $(S)/common/%.o,$(LIB_OBJ_S))
common_mpi: $(filter $(M)/common/%.o,$(LIB_OBJ_M))
match_test: bin/match_test
units_test: bin/units_test
coupling_test: bin/coupling_test
iface_law_test: bin/iface_law_test

clean:
	rm -rf build bin

help:
	@echo "MixNSSolver build targets:"
	@echo "  make / make all        serial mixed solver         (bin/mixsolver)"
	@echo "  make mpi               MPI    mixed solver         (bin/mixsolver_mpi)"
	@echo "  make structured        serial structured solver    (bin/struct_solver)"
	@echo "  make structured_mpi    MPI    structured solver"
	@echo "  make unstructured      serial unstructured solver  (bin/uns_solver)"
	@echo "  make unstructured_mpi  MPI    unstructured solver"
	@echo "  make common[_mpi]      compile common modules only"
	@echo "  make clean             remove build/ and bin/"
	@echo "Options: DEBUG=1 (debug flags)"
	@echo "Parallel: use 'make -j'; for the very first build after adding many new"
	@echo "          interdependent modules, prefer 'make -j1' once (see Makefile)."
	@echo ""
	@echo "Compiler : $(FC) / $(MPIFC)"
	@echo "Serial   : $(filter-out %_mpi.f90,$(notdir $(LIB_SRCS_S)))"
	@echo "MPI-only : $(notdir $(filter %_mpi.f90,$(LIB_SRCS_M)))"

# -----------------------------------------------------------------------------
# Pristine-build edges (see header note 5)
# -----------------------------------------------------------------------------
# Every object waits for the foundational module(s); this is a REAL edge (unlike
# list ordering), so it is safe under 'make -j' on a tree without .d files.
# It costs nothing incrementally: precision changes only when kinds change,
# in which case a full rebuild is correct anyway.
BOOT_OBJ_S := $(patsubst src/%.f90,$(S)/%.o,$(BOOTSTRAP_ORDER))
BOOT_OBJ_M := $(patsubst src/%.f90,$(M)/%.o,$(BOOTSTRAP_ORDER))

ALL_MAIN_S := $(patsubst src/%.f90,$(S)/%.o,$(MAIN_MIX_F) $(MAIN_STRUCT_F) $(MAIN_UNS_F) $(MAIN_DISPATCH_F))
ALL_MAIN_M := $(patsubst src/%.f90,$(M)/%.o,$(MAIN_MIX_F) $(MAIN_STRUCT_F) $(MAIN_UNS_F) $(MAIN_DISPATCH_F))

$(filter-out $(BOOT_OBJ_S),$(LIB_OBJ_S) $(ALL_MAIN_S)): $(BOOT_OBJ_S)
$(filter-out $(BOOT_OBJ_M),$(LIB_OBJ_M) $(ALL_MAIN_M)): $(BOOT_OBJ_M)

# Structured-solver internal module chain (phase 2b modularization complete:
# all 29 free sub_*.f90 are encapsulated in mod_struct_* modules).
# Layers are the real use-edges in conservative total order, which guarantees
# a clean 'make -j' succeeds before any .d file exists:
#   L0 precision
#   L1 constants / types / fdm_data / flowvar
#   L2 global
#   L3 scheme / flux / fdm / time / bc / mpi / grid
#   L4 solver / io
#   L5 init
# main waits for every module layer.
ST_LAYER0 := mod_struct_precision
ST_LAYER1 := mod_struct_constants mod_struct_types mod_struct_fdm_data mod_struct_flowvar
ST_LAYER2 := mod_struct_global
ST_LAYER3 := mod_struct_scheme mod_struct_flux mod_struct_fdm mod_struct_time \
             mod_struct_bc mod_struct_mpi mod_struct_grid
ST_LAYER4 := mod_struct_solver mod_struct_io
ST_LAYER5 := mod_struct_init
ST_LAYER6 := mod_struct_driver

st_objs = $(foreach b,$(1),$(S)/structured/$(b).o)
st_objm = $(foreach b,$(1),$(M)/structured/$(b).o)

$(call st_objs,$(ST_LAYER1)): $(call st_objs,$(ST_LAYER0))
$(call st_objs,$(ST_LAYER2)): $(call st_objs,$(ST_LAYER0) $(ST_LAYER1))
$(call st_objs,$(ST_LAYER3)): $(call st_objs,$(ST_LAYER0) $(ST_LAYER1) $(ST_LAYER2))
$(call st_objs,$(ST_LAYER4)): $(call st_objs,$(ST_LAYER0) $(ST_LAYER1) $(ST_LAYER2) $(ST_LAYER3))
$(call st_objs,$(ST_LAYER5)): $(call st_objs,$(ST_LAYER0) $(ST_LAYER1) $(ST_LAYER2) $(ST_LAYER3) $(ST_LAYER4))
$(call st_objs,$(ST_LAYER6)): $(call st_objs,$(ST_LAYER0) $(ST_LAYER1) $(ST_LAYER2) $(ST_LAYER3) $(ST_LAYER4) $(ST_LAYER5))
$(S)/structured/main.o: $(call st_objs,$(ST_LAYER0) $(ST_LAYER1) $(ST_LAYER2) \
                                    $(ST_LAYER3) $(ST_LAYER4) $(ST_LAYER5))

$(call st_objm,$(ST_LAYER1)): $(call st_objm,$(ST_LAYER0))
$(call st_objm,$(ST_LAYER2)): $(call st_objm,$(ST_LAYER0) $(ST_LAYER1))
$(call st_objm,$(ST_LAYER3)): $(call st_objm,$(ST_LAYER0) $(ST_LAYER1) $(ST_LAYER2))
$(call st_objm,$(ST_LAYER4)): $(call st_objm,$(ST_LAYER0) $(ST_LAYER1) $(ST_LAYER2) $(ST_LAYER3))
$(call st_objm,$(ST_LAYER5)): $(call st_objm,$(ST_LAYER0) $(ST_LAYER1) $(ST_LAYER2) $(ST_LAYER3) $(ST_LAYER4))
$(call st_objm,$(ST_LAYER6)): $(call st_objm,$(ST_LAYER0) $(ST_LAYER1) $(ST_LAYER2) $(ST_LAYER3) $(ST_LAYER4) $(ST_LAYER5))
$(M)/structured/main.o: $(call st_objm,$(ST_LAYER0) $(ST_LAYER1) $(ST_LAYER2) \
                                    $(ST_LAYER3) $(ST_LAYER4) $(ST_LAYER5))

# Common-layer modules (precision / constants / interface) precede every
# structured object: the structured solver uses const_var, precision_EC and
# (phase 2b s4b) mod_interface.  These are additive prerequisite edges, so a
# clean 'make -j' orders mod_interface before mod_struct_grid/init/bc even
# before any .d file exists.  (Common layer never depends on structured, so
# no cycle is introduced.)
COMMON_OBJ_S := $(patsubst src/%.f90,$(S)/%.o,$(COMMON_F))
COMMON_OBJ_M := $(patsubst src/%.f90,$(M)/%.o,$(COMMON_F))
$(call st_objs,$(ST_LAYER0) $(ST_LAYER1) $(ST_LAYER2) $(ST_LAYER3) \
  $(ST_LAYER4) $(ST_LAYER5) $(ST_LAYER6)) $(S)/structured/main.o: $(COMMON_OBJ_S)
$(call st_objm,$(ST_LAYER0) $(ST_LAYER1) $(ST_LAYER2) $(ST_LAYER3) \
  $(ST_LAYER4) $(ST_LAYER5) $(ST_LAYER6)) $(M)/structured/main.o: $(COMMON_OBJ_M)

# Unstructured-solver internal module chain (phase 3).
# Layers are the real use-edges in conservative total order, which guarantees
# a clean 'make -j' succeeds before any .d file exists.
#
# Serial tree: *_mpi.f90 modules are excluded, so the chain is shorter.
# MPI tree: all modules including MPI-only ones.
UNS_LAYER0_S := mod_uns_mesh mod_uns_control mod_uns_linsolver
UNS_LAYER1_S := mod_uns_cas_reader mod_uns_connectivity mod_uns_geometry
UNS_LAYER2_S := mod_uns_bc
UNS_LAYER3_S := mod_uns_fields
UNS_LAYER4_S := mod_uns_forces mod_uns_output
UNS_LAYER5_S := mod_uns_simple
UNS_LAYER6_S := mod_uns_driver

UNS_LAYER0_M := mod_uns_mesh mod_uns_control mod_uns_linsolver
UNS_LAYER1_M := mod_uns_mpi_core mod_uns_metis_iface mod_uns_cas_reader \
                mod_uns_connectivity mod_uns_geometry
UNS_LAYER2_M := mod_uns_bc
UNS_LAYER3_M := mod_uns_fields
UNS_LAYER4_M := mod_uns_local_mesh mod_uns_forces
UNS_LAYER5_M := mod_uns_halo mod_uns_output mod_uns_partition
UNS_LAYER6_M := mod_uns_linsolver_mpi mod_uns_gather mod_uns_restart
UNS_LAYER7_M := mod_uns_simple
UNS_LAYER8_M := mod_uns_simple_mpi
UNS_LAYER9_M := mod_uns_driver

uns_objs = $(foreach b,$(1),$(S)/unstructured/$(b).o)
uns_objm = $(foreach b,$(1),$(M)/unstructured/$(b).o)

# Serial pristine edges
$(call uns_objs,$(UNS_LAYER1_S)): $(call uns_objs,$(UNS_LAYER0_S))
$(call uns_objs,$(UNS_LAYER2_S)): $(call uns_objs,$(UNS_LAYER0_S) $(UNS_LAYER1_S))
$(call uns_objs,$(UNS_LAYER3_S)): $(call uns_objs,$(UNS_LAYER0_S) $(UNS_LAYER1_S) $(UNS_LAYER2_S))
$(call uns_objs,$(UNS_LAYER4_S)): $(call uns_objs,$(UNS_LAYER0_S) $(UNS_LAYER1_S) $(UNS_LAYER2_S) $(UNS_LAYER3_S))
$(call uns_objs,$(UNS_LAYER5_S)): $(call uns_objs,$(UNS_LAYER0_S) $(UNS_LAYER1_S) $(UNS_LAYER2_S) $(UNS_LAYER3_S) $(UNS_LAYER4_S))
$(call uns_objs,$(UNS_LAYER6_S)): $(call uns_objs,$(UNS_LAYER0_S) $(UNS_LAYER1_S) $(UNS_LAYER2_S) $(UNS_LAYER3_S) $(UNS_LAYER4_S) $(UNS_LAYER5_S))
$(S)/unstructured/main_uns.o: $(call uns_objs,$(UNS_LAYER0_S) $(UNS_LAYER1_S) $(UNS_LAYER2_S) \
                                        $(UNS_LAYER3_S) $(UNS_LAYER4_S) $(UNS_LAYER5_S))

# MPI pristine edges
$(call uns_objm,$(UNS_LAYER1_M)): $(call uns_objm,$(UNS_LAYER0_M))
$(call uns_objm,$(UNS_LAYER2_M)): $(call uns_objm,$(UNS_LAYER0_M) $(UNS_LAYER1_M))
$(call uns_objm,$(UNS_LAYER3_M)): $(call uns_objm,$(UNS_LAYER0_M) $(UNS_LAYER1_M) $(UNS_LAYER2_M))
$(call uns_objm,$(UNS_LAYER4_M)): $(call uns_objm,$(UNS_LAYER0_M) $(UNS_LAYER1_M) $(UNS_LAYER2_M) $(UNS_LAYER3_M))
$(call uns_objm,$(UNS_LAYER5_M)): $(call uns_objm,$(UNS_LAYER0_M) $(UNS_LAYER1_M) $(UNS_LAYER2_M) $(UNS_LAYER3_M) $(UNS_LAYER4_M))
$(call uns_objm,$(UNS_LAYER6_M)): $(call uns_objm,$(UNS_LAYER0_M) $(UNS_LAYER1_M) $(UNS_LAYER2_M) $(UNS_LAYER3_M) $(UNS_LAYER4_M) $(UNS_LAYER5_M))
$(call uns_objm,$(UNS_LAYER7_M)): $(call uns_objm,$(UNS_LAYER0_M) $(UNS_LAYER1_M) $(UNS_LAYER2_M) $(UNS_LAYER3_M) $(UNS_LAYER4_M) $(UNS_LAYER5_M) $(UNS_LAYER6_M))
$(call uns_objm,$(UNS_LAYER8_M)): $(call uns_objm,$(UNS_LAYER0_M) $(UNS_LAYER1_M) $(UNS_LAYER2_M) $(UNS_LAYER3_M) $(UNS_LAYER4_M) $(UNS_LAYER5_M) $(UNS_LAYER6_M) $(UNS_LAYER7_M))
$(call uns_objm,$(UNS_LAYER9_M)): $(call uns_objm,$(UNS_LAYER0_M) $(UNS_LAYER1_M) $(UNS_LAYER2_M) $(UNS_LAYER3_M) $(UNS_LAYER4_M) $(UNS_LAYER5_M) $(UNS_LAYER6_M) $(UNS_LAYER7_M) $(UNS_LAYER8_M))
$(M)/unstructured/main_uns_mpi.o: $(call uns_objm,$(UNS_LAYER0_M) $(UNS_LAYER1_M) $(UNS_LAYER2_M) \
                                        $(UNS_LAYER3_M) $(UNS_LAYER4_M) $(UNS_LAYER5_M) $(UNS_LAYER6_M) $(UNS_LAYER7_M) $(UNS_LAYER8_M))

# Coupling-layer modules (phase 5-6): internal dependencies.
# mod_interface_units  <- common (mod_reference_state)
# mod_interface_exchange <- common (mod_interface)
# mod_coupling_exchange  <- mod_interface_units + mod_interface_exchange + mpi
COUPL_LAYER0 := mod_interface_units mod_interface_exchange
COUPL_LAYER1 := mod_coupling_exchange
# mod_mix_driver: the coupling group drivers extracted from main.f90. Its two
# `use` edges are mod_struct_driver / mod_uns_driver (both already transitively
# ordered by COUPL_LAYER0/1's prerequisites) plus the exchange layer.
COUPL_LAYER2 := mod_mix_driver

coupl_objs = $(foreach b,$(1),$(S)/coupling/$(b).o)
coupl_objm = $(foreach b,$(1),$(M)/coupling/$(b).o)

$(call coupl_objs,$(COUPL_LAYER1)): $(call coupl_objs,$(COUPL_LAYER0))
$(call coupl_objm,$(COUPL_LAYER1)): $(call coupl_objm,$(COUPL_LAYER0))
$(call coupl_objs,$(COUPL_LAYER2)): $(call coupl_objs,$(COUPL_LAYER0) $(COUPL_LAYER1))
$(call coupl_objm,$(COUPL_LAYER2)): $(call coupl_objm,$(COUPL_LAYER0) $(COUPL_LAYER1))

# Coupling modules depend on common + structured + unstructured layers.
$(call coupl_objs,$(COUPL_LAYER0) $(COUPL_LAYER1)): $(COMMON_OBJ_S) \
  $(call st_objs,$(ST_LAYER0) $(ST_LAYER1) $(ST_LAYER2) $(ST_LAYER3) $(ST_LAYER4) $(ST_LAYER5) $(ST_LAYER6)) \
  $(call uns_objs,$(UNS_LAYER0_S) $(UNS_LAYER1_S) $(UNS_LAYER2_S) $(UNS_LAYER3_S) $(UNS_LAYER4_S) $(UNS_LAYER5_S) $(UNS_LAYER6_S))
$(call coupl_objm,$(COUPL_LAYER0) $(COUPL_LAYER1)): $(COMMON_OBJ_M) \
  $(call st_objm,$(ST_LAYER0) $(ST_LAYER1) $(ST_LAYER2) $(ST_LAYER3) $(ST_LAYER4) $(ST_LAYER5) $(ST_LAYER6)) \
  $(call uns_objm,$(UNS_LAYER0_M) $(UNS_LAYER1_M) $(UNS_LAYER2_M) $(UNS_LAYER3_M) $(UNS_LAYER4_M) $(UNS_LAYER5_M) $(UNS_LAYER6_M) $(UNS_LAYER7_M) $(UNS_LAYER8_M) $(UNS_LAYER9_M))

# Mixed driver (phase 6): main.f90 'uses' mod_struct_driver, mod_uns_driver and
# mod_coupling_exchange.  The coupling objects above already transitively follow
# common + structured + unstructured, so a single edge to the coupling layer
# orders every prerequisite on a pristine tree before any .d file exists.
$(S)/main.o: $(call coupl_objs,$(COUPL_LAYER0) $(COUPL_LAYER1) $(COUPL_LAYER2))
$(M)/main.o: $(call coupl_objm,$(COUPL_LAYER0) $(COUPL_LAYER1) $(COUPL_LAYER2))
# Self-dispatching main (bin/mixnsolver): needs mod_mix_driver too.
$(S)/main_dispatch.o: $(call coupl_objs,$(COUPL_LAYER0) $(COUPL_LAYER1) $(COUPL_LAYER2))
$(M)/main_dispatch.o: $(call coupl_objm,$(COUPL_LAYER0) $(COUPL_LAYER1) $(COUPL_LAYER2))

# phase-5 units/exchange test main: same pristine-ordering need -- its .d file
# does not exist yet, so order it after the coupling layer (which itself follows
# common + structured + unstructured).
$(S)/coupling/test_units_exchange.o: $(call coupl_objs,$(COUPL_LAYER0) $(COUPL_LAYER1))

# Common-layer modules precede every unstructured object.
$(call uns_objs,$(UNS_LAYER0_S) $(UNS_LAYER1_S) $(UNS_LAYER2_S) $(UNS_LAYER3_S) \
  $(UNS_LAYER4_S) $(UNS_LAYER5_S) $(UNS_LAYER6_S)) $(S)/unstructured/main_uns.o: $(COMMON_OBJ_S)
$(call uns_objm,$(UNS_LAYER0_M) $(UNS_LAYER1_M) $(UNS_LAYER2_M) $(UNS_LAYER3_M) \
  $(UNS_LAYER4_M) $(UNS_LAYER5_M) $(UNS_LAYER6_M) $(UNS_LAYER7_M) $(UNS_LAYER8_M) $(UNS_LAYER9_M)) \
  $(M)/unstructured/main_uns_mpi.o: $(COMMON_OBJ_M)

# -----------------------------------------------------------------------------
# Auto-generated module dependencies
# -----------------------------------------------------------------------------
-include $(wildcard $(S)/*/*.d $(M)/*/*.d)
